### ISSUE TITLE
support linuxmint

### ISSUE THREAD

**Issue by tiancj** [ambition-echo/earth_wallpaper#2]
Thanks for wonderful app! Can you add support for Linuxmint cinnamon DE?

You may add the following code to `scripts/setWallpaper.py`.

```py
    elif (DE == 'X-Cinnamon'):
        gs = "gsettings set org.cinnamon.desktop.background picture-uri file://{}".format(file)
        os.system(gs)
```

**Comment by tiancj** [comment]
In addition, a sub-Category can be added to .desktop file, for example, Network. In this way, startup menu will place earth_wallpaper under Network categories.
```
Categories=Application;Network;
```

**Comment by ambition-echo** [comment]
> Thanks for wonderful app! Can you add support for Linuxmint cinnamon DE?
> 
> You may add the following code to `scripts/setWallpaper.py`.
> 
> ```py
>     elif (DE == 'X-Cinnamon'):
>         gs = "gsettings set org.cinnamon.desktop.background picture-uri file://{}".format(file)
>         os.system(gs)
> ```

ok i forgot about this, i tested linuxmint with only xfce in mind, i'll add it later today, or you can submit a pr

**Comment by ambition-echo** [comment]
> In addition, a sub-Category can be added to .desktop file, for example, Network. In this way, startup menu will place earth_wallpaper under Network categories.
> ```
> Categories=Application;Network;
> ```
> 

good idea!
i will do it
