### ISSUE TITLE
希望增加一个能设置壁纸脚本的入口

### ISSUE THREAD

**Issue by jiyi** [ambition-echo/earth_wallpaper#25]
很棒的壁纸软件
我使用的操作系统是archlinux和i3wm，设置壁纸使用feh。如果想正常使用的话，需要手工更改代码。
能否增加一个设置项，用来读取运行放在配置文件夹里的脚本文件，类似utils/xfce.sh，从而可以自定义如何设置壁纸。
谢谢

**Comment by ambition-echo** [comment]
需要新增支持的桌面的话，你可以来个提交个PR,或者说具体说一下设置的方法我来写，我不知道你说的使用feh
具体是怎么操作

**Comment by ambition-echo** [comment]
我觉得这是你环境的设置问题，不应该由软件来解决，最好的情况应该是让软件正确识别

**Comment by jiyi** [comment]
我喜欢xfce和i3，所以环境设置是不会改的。我也喜欢这个软件，继续改代码用下去不是问题。
i3只是一个桌面管理器，没有自己的壁纸功能，不同的人设置壁纸的方式不尽相同，针对这种小众桌面是没有一个统一的解决办法的，希望理解。

**Comment by ambition-echo** [comment]
这样啊，没怎么用过这种窗口管理器

**Comment by ambition-echo** [comment]
nightly版本已经更新，有什么问题欢迎继续反馈

**Comment by jiyi** [comment]
感谢，已更新，可以使用，赞

**Comment by ambition-echo** [comment]
这不得给个star
