### ISSUE TITLE
向日葵8号的壁纸目前无法更新

### ISSUE THREAD

**Issue by shootheart** [ambition-echo/earth_wallpaper#27]
向日葵8号的图片更新貌似延迟了，差不多每个整十分的时间点更新20分钟前的画面，如下图（我开了自动刷新）

![img](https://dylanblog.oss-cn-beijing.aliyuncs.com/2022-12-01_22-19.png)

**Comment by ambition-echo** [comment]
是有延迟的，他没有实时存档的，延迟应该是半小时

**Comment by shootheart** [comment]
还有个问题。。填充黑色区域后的图片应该是没有保存，所以现在壁纸显示的是下载的原图。。

**Comment by ambition-echo** [comment]
你用的是哪个版本呢

**Comment by ambition-echo** [comment]
已修复

**Comment by shootheart** [comment]
多谢，关于延迟的问题，我看现在获取图片是当前时间前推最近的整十分时间点，网站延迟要比这个时间长，所以下载的图片是空的，建议这个时间再往前推，应该至少要20分钟

**Comment by ambition-echo** [comment]
已修
