### ISSUE TITLE
作者的deepin是如何美化的？

### ISSUE THREAD

**Issue by EchoGroot** [ambition-echo/earth_wallpaper#29]
顶栏和dock栏好特别，可以分享下吗？

**Comment by ambition-echo** [comment]
不好意思，用的不是deepin,是arch+KDE

**Comment by zhanglongqi** [comment]
我也看上了顶栏配置,好看

**Comment by ambition-echo** [comment]
其实就是kde的任务栏移上去的，找了一下，之前写文章记录过，希望有所帮助
[https://blog.huguoyang.cn/p/kde%E7%BE%8E%E5%8C%96%E8%AE%B0%E5%BD%95](https://blog.huguoyang.cn/p/kde%E7%BE%8E%E5%8C%96%E8%AE%B0%E5%BD%95/)

**Comment by EchoGroot** [comment]
3q
