### ISSUE TITLE
arhlinux aur 安装需要输入 jihulab.com 账号

### ISSUE THREAD

**Issue by jiyi** [ambition-echo/earth_wallpaper#32]
archlinux aur 里升级 earth-wallpaper-nightly 包，提示 “Username for 'https://jihulab.com':" 需要输入

**Comment by ambition-echo** [comment]
不好意思，jihu注销了，忘了把aur包地址改到github了。

**Comment by ambition-echo** [comment]
已修

**Comment by ambition-echo** [comment]
应该没问题了，有问题欢迎来反馈
