### ISSUE TITLE
cant install in ubuntu20.04

### ISSUE THREAD

**Issue by zst-z** [ambition-echo/earth_wallpaper#7]
RT 
this is the error:
下列软件包有未满足的依赖关系：
 earth-wallpaper : 依赖: qdbus 但无法安装它
i have tried to isntall the qdbus using the "sudo apt install qdbus" but didnt work.here is the error:
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
没有可用的软件包 qdbus，但是它被其它的软件包引用了。
这可能意味着这个缺失的软件包可能已被废弃，
或者只能在其他发布源中找到
E: 软件包 qdbus 没有可安装候选 

解决方案：
- [x] 弃用qdbus，改用python ```dbus``` 库
- [x] 降低构建环境Qt版本

**Comment by ambition-echo** [comment]
ubuntu仓库里面应该是有qdbus的呀，```sudo apt update```再试试呢，还有是不是你的sources.list有问题呢，检查一下。

**Comment by ambition-echo** [comment]
刚刚看了一下，Ubuntu20.04 仓库确实没有qdbus，而且仓库里的Qt版本也比较低，我会尝试解决，但还是推荐使用最新版系统

**Comment by puzzle9** [comment]
一个优秀的开发者 还需要自己上传`aur` 天哪 加油

**Comment by ambition-echo** [comment]
> 一个优秀的开发者 还需要自己上传`aur` 天哪 加油

啊这，感谢支持😃

**Comment by ambition-echo** [comment]
- [ ] 弃用qdbus，改用python ```dbus``` 库
- [ ] 降低构建环境Qt版本
